// FlEq display: M3 Expressive spring -> CSS linear() easing generator.
// 物理パラメータ (stiffness/damping) から damped spring の単位ステップ応答を
// サンプリングし linear() 点列を出力する。再生成は `node display/scripts/generate-springs.mjs`。
// 出力を display/frontend/src/lib/theme.css の spring トークンへ貼る。
function springPos(t, wn, zeta) {
  if (zeta < 1) {
    const wd = wn * Math.sqrt(1 - zeta * zeta);
    return 1 - Math.exp(-zeta * wn * t) * (Math.cos(wd * t) + (zeta * wn / wd) * Math.sin(wd * t));
  }
  return 1 - Math.exp(-wn * t) * (1 + wn * t); // critically damped (zeta = 1)
}
function springLinear({ stiffness, damping, mass = 1, stops = 24, settle = 0.001 }) {
  const wn = Math.sqrt(stiffness / mass);
  const zeta = damping;
  const dt = 0.0005;
  let tEnd = dt;
  for (let t = 0; t < 10; t += dt) {
    if (Math.abs(springPos(t, wn, zeta) - 1) >= settle) tEnd = t + dt; // 最後に band を出る時刻
  }
  const pts = [];
  for (let i = 0; i <= stops; i++) pts.push(Math.round(springPos((i / stops) * tEnd, wn, zeta) * 10000) / 10000);
  return { linear: `linear(${pts.join(", ")})`, durMs: Math.round(tEnd * 1000), wn };
}
export const SPRING_SPECS = {
  "spring-spatial-default": { stiffness: 380, damping: 0.8 }, // 位置・スケール, overshoot あり
  "spring-spatial-quick": { stiffness: 3600, damping: 0.8 }, // 緊急入場の短い味付け (~142ms)
  "spring-spatial-slow": { stiffness: 200, damping: 0.8 },
  "spring-effects-default": { stiffness: 1600, damping: 1.0 }, // 色・不透明度, overshoot 禁止
  "spring-effects-slow": { stiffness: 800, damping: 1.0 },
};

export function computeAll() {
  const out = {};
  for (const [name, p] of Object.entries(SPRING_SPECS)) out[name] = springLinear(p);
  return out; // { [name]: { linear, durMs, wn } }
}

export function renderCssBlock() {
  const all = computeAll();
  return Object.entries(all)
    .map(([name, r]) => {
      const p = SPRING_SPECS[name];
      return `  /* ${name}: stiffness=${p.stiffness} damping=${p.damping} wn=${r.wn.toFixed(2)} settle=~${r.durMs}ms */\n  --${name}: ${r.linear};\n  --${name}-dur: ${r.durMs}ms;`;
    })
    .join("\n");
}

export function renderMotionGeneratedTs() {
  const all = computeAll();
  const durs = Object.fromEntries(Object.entries(all).map(([n, r]) => [n, r.durMs]));
  const linears = Object.fromEntries(Object.entries(all).map(([n, r]) => [n, r.linear]));
  return [
    "// AUTO-GENERATED by display/scripts/generate-springs.mjs --write. 手編集しない。",
    "// spring 物理 (SPRING_SPECS) から算出した duration/linear() の唯一の生成物。",
    `export const SPRING_SPECS = ${JSON.stringify(SPRING_SPECS, null, 2)} as const;`,
    `export const SPRING_DURATIONS_MS: Record<string, number> = ${JSON.stringify(durs, null, 2)};`,
    `export const SPRING_LINEARS: Record<string, string> = ${JSON.stringify(linears, null, 2)};`,
    "",
  ].join("\n");
}

const START = "/* GENERATED:springs:start (generate-springs.mjs --write) */";
const END = "/* GENERATED:springs:end */";

/** theme.css の spring 区間を安全に差し替える。マーカー不正なら書込み前に throw する。 */
export function replaceCssSpringBlock(css) {
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`${esc(START)}[\\s\\S]*?${esc(END)}`);
  if (!re.test(css)) throw new Error("theme.css に GENERATED:springs マーカーが無い");
  return css.replace(re, `${START}\n${renderCssBlock()}\n  ${END}`);
}

/**
 * 全入力を検証し次の二出力を確定してから書き込む。theme.css のマーカー欠損などで
 * 検証が失敗した場合、motion.generated.ts だけが更新される部分更新を防ぐ。
 */
export function writeGenerated({ readCss, writeCss, writeMotion }) {
  const nextCss = replaceCssSpringBlock(readCss());
  const nextMotion = renderMotionGeneratedTs();
  writeMotion(nextMotion);
  writeCss(nextCss);
}

// CLI: 直接実行時のみ副作用を出す (import (テスト/生成物) では出さない)
if (process.argv[1] && (await import("node:url")).fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes("--write")) {
    const { fileURLToPath } = await import("node:url");
    const { writeFileSync, readFileSync } = await import("node:fs");
    const genOut = fileURLToPath(new URL("../frontend/src/lib/motion.generated.ts", import.meta.url));
    const cssPath = fileURLToPath(new URL("../frontend/src/lib/theme.css", import.meta.url));
    writeGenerated({
      readCss: () => readFileSync(cssPath, "utf-8"),
      writeCss: (css) => writeFileSync(cssPath, css),
      writeMotion: (motion) => writeFileSync(genOut, motion),
    });
    console.error("wrote motion.generated.ts + theme.css spring block");
  } else {
    console.log(renderCssBlock()); // 確認用に stdout へ (--write なしのとき)
  }
}
