// AUTO-GENERATED by display/scripts/generate-springs.mjs --write. 手編集しない。
// spring 物理 (SPRING_SPECS) から算出した duration/linear() の唯一の生成物。
export const SPRING_SPECS = {
  "spring-spatial-default": {
    "stiffness": 380,
    "damping": 0.8
  },
  "spring-spatial-quick": {
    "stiffness": 3600,
    "damping": 0.8
  },
  "spring-spatial-slow": {
    "stiffness": 200,
    "damping": 0.8
  },
  "spring-effects-default": {
    "stiffness": 1600,
    "damping": 1
  },
  "spring-effects-slow": {
    "stiffness": 800,
    "damping": 1
  }
} as const;
export const SPRING_DURATIONS_MS: Record<string, number> = {
  "spring-spatial-default": 435,
  "spring-spatial-quick": 142,
  "spring-spatial-slow": 599,
  "spring-effects-default": 231,
  "spring-effects-slow": 327
};
export const SPRING_LINEARS: Record<string, string> = {
  "spring-spatial-default": "linear(0, 0.0516, 0.1705, 0.3163, 0.4636, 0.598, 0.7123, 0.8044, 0.8751, 0.9271, 0.9636, 0.9877, 1.0026, 1.0108, 1.0144, 1.0151, 1.0141, 1.0122, 1.01, 1.0077, 1.0058, 1.0041, 1.0027, 1.0017, 1.001)",
  "spring-spatial-quick": "linear(0, 0.0517, 0.1708, 0.3168, 0.4643, 0.5988, 0.713, 0.805, 0.8757, 0.9276, 0.9639, 0.9879, 1.0027, 1.0109, 1.0145, 1.0151, 1.0141, 1.0122, 1.0099, 1.0077, 1.0057, 1.004, 1.0027, 1.0017, 1.001)",
  "spring-spatial-slow": "linear(0, 0.0516, 0.1704, 0.3162, 0.4635, 0.5979, 0.7122, 0.8043, 0.875, 0.9271, 0.9635, 0.9877, 1.0025, 1.0108, 1.0144, 1.0151, 1.0141, 1.0122, 1.01, 1.0078, 1.0058, 1.0041, 1.0028, 1.0017, 1.001)",
  "spring-effects-default": "linear(0, 0.0576, 0.1805, 0.3211, 0.4555, 0.5733, 0.6714, 0.7504, 0.8125, 0.8604, 0.8968, 0.9242, 0.9446, 0.9597, 0.9708, 0.979, 0.9849, 0.9892, 0.9922, 0.9945, 0.9961, 0.9972, 0.998, 0.9986, 0.999)",
  "spring-effects-slow": "linear(0, 0.0575, 0.1803, 0.3208, 0.4552, 0.573, 0.6711, 0.7502, 0.8122, 0.8602, 0.8966, 0.9241, 0.9445, 0.9596, 0.9708, 0.9789, 0.9848, 0.9891, 0.9922, 0.9944, 0.996, 0.9972, 0.998, 0.9986, 0.999)"
};
